import Head from 'next/head';

const Home = () => (
  <>
    <Head>
      <title>Web3Ocean</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <div>
      <h1 className="text-3xl font-bold underline">Hello</h1>
    </div>
  </>
);

export default Home;
